// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventKind int32

const (
	EventKind_EventKindStageStarted  EventKind = 0
	EventKind_EventKindStageFinished EventKind = 1
	EventKind_EventKindGenericUpdate EventKind = 2
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EventKindStageStarted",
		1: "EventKindStageFinished",
		2: "EventKindGenericUpdate",
	}
	EventKind_value = map[string]int32{
		"EventKindStageStarted":  0,
		"EventKindStageFinished": 1,
		"EventKindGenericUpdate": 2,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EventKind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EventKind(num)
	return nil
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type EventStatus int32

const (
	EventStatus_EventStatusSuccess EventStatus = 0
	EventStatus_EventStatusFailure EventStatus = 1
)

// Enum value maps for EventStatus.
var (
	EventStatus_name = map[int32]string{
		0: "EventStatusSuccess",
		1: "EventStatusFailure",
	}
	EventStatus_value = map[string]int32{
		"EventStatusSuccess": 0,
		"EventStatusFailure": 1,
	}
)

func (x EventStatus) Enum() *EventStatus {
	p := new(EventStatus)
	*p = x
	return p
}

func (x EventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[1].Descriptor()
}

func (EventStatus) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[1]
}

func (x EventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EventStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EventStatus(num)
	return nil
}

// Deprecated: Use EventStatus.Descriptor instead.
func (EventStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

type RawEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RawEvent            `protobuf:"bytes,1,rep,name=Events" json:"Events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawEvents) Reset() {
	*x = RawEvents{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawEvents) ProtoMessage() {}

func (x *RawEvents) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawEvents.ProtoReflect.Descriptor instead.
func (*RawEvents) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *RawEvents) GetEvents() []*RawEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type RawEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecID        *string                `protobuf:"bytes,1,req,name=ExecID" json:"ExecID,omitempty"`
	ProcessID     []byte                 `protobuf:"bytes,2,req,name=ProcessID" json:"ProcessID,omitempty"`
	ExecutorID    *string                `protobuf:"bytes,3,req,name=ExecutorID" json:"ExecutorID,omitempty"`
	Stage         *RawStage              `protobuf:"bytes,4,req,name=Stage" json:"Stage,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,5,req,name=Ts" json:"Ts,omitempty"`
	Kind          *EventKind             `protobuf:"varint,6,req,name=Kind,enum=api.EventKind" json:"Kind,omitempty"`
	Status        *EventStatus           `protobuf:"varint,7,req,name=Status,enum=api.EventStatus" json:"Status,omitempty"`
	Input         []byte                 `protobuf:"bytes,8,opt,name=Input" json:"Input,omitempty"`
	Output        []byte                 `protobuf:"bytes,9,opt,name=Output" json:"Output,omitempty"`
	Failure       []byte                 `protobuf:"bytes,10,opt,name=Failure" json:"Failure,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,11,opt,name=Metadata" json:"Metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawEvent) Reset() {
	*x = RawEvent{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawEvent) ProtoMessage() {}

func (x *RawEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawEvent.ProtoReflect.Descriptor instead.
func (*RawEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *RawEvent) GetExecID() string {
	if x != nil && x.ExecID != nil {
		return *x.ExecID
	}
	return ""
}

func (x *RawEvent) GetProcessID() []byte {
	if x != nil {
		return x.ProcessID
	}
	return nil
}

func (x *RawEvent) GetExecutorID() string {
	if x != nil && x.ExecutorID != nil {
		return *x.ExecutorID
	}
	return ""
}

func (x *RawEvent) GetStage() *RawStage {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *RawEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *RawEvent) GetKind() EventKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return EventKind_EventKindStageStarted
}

func (x *RawEvent) GetStatus() EventStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return EventStatus_EventStatusSuccess
}

func (x *RawEvent) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RawEvent) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *RawEvent) GetFailure() []byte {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *RawEvent) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RawStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Description   *string                `protobuf:"bytes,2,req,name=Description" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawStage) Reset() {
	*x = RawStage{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawStage) ProtoMessage() {}

func (x *RawStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawStage.ProtoReflect.Descriptor instead.
func (*RawStage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *RawStage) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RawStage) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\tRawEvents\x12%\n" +
	"\x06Events\x18\x01 \x03(\v2\r.api.RawEventR\x06Events\"\xe3\x02\n" +
	"\bRawEvent\x12\x16\n" +
	"\x06ExecID\x18\x01 \x02(\tR\x06ExecID\x12\x1c\n" +
	"\tProcessID\x18\x02 \x02(\fR\tProcessID\x12\x1e\n" +
	"\n" +
	"ExecutorID\x18\x03 \x02(\tR\n" +
	"ExecutorID\x12#\n" +
	"\x05Stage\x18\x04 \x02(\v2\r.api.RawStageR\x05Stage\x12*\n" +
	"\x02Ts\x18\x05 \x02(\v2\x1a.google.protobuf.TimestampR\x02Ts\x12\"\n" +
	"\x04Kind\x18\x06 \x02(\x0e2\x0e.api.EventKindR\x04Kind\x12(\n" +
	"\x06Status\x18\a \x02(\x0e2\x10.api.EventStatusR\x06Status\x12\x14\n" +
	"\x05Input\x18\b \x01(\fR\x05Input\x12\x16\n" +
	"\x06Output\x18\t \x01(\fR\x06Output\x12\x18\n" +
	"\aFailure\x18\n" +
	" \x01(\fR\aFailure\x12\x1a\n" +
	"\bMetadata\x18\v \x01(\fR\bMetadata\"@\n" +
	"\bRawStage\x12\x12\n" +
	"\x04Name\x18\x01 \x02(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x02(\tR\vDescription*^\n" +
	"\tEventKind\x12\x19\n" +
	"\x15EventKindStageStarted\x10\x00\x12\x1a\n" +
	"\x16EventKindStageFinished\x10\x01\x12\x1a\n" +
	"\x16EventKindGenericUpdate\x10\x02*=\n" +
	"\vEventStatus\x12\x16\n" +
	"\x12EventStatusSuccess\x10\x00\x12\x16\n" +
	"\x12EventStatusFailure\x10\x012<\n" +
	"\x03API\x125\n" +
	"\tSendEvent\x12\x0e.api.RawEvents\x1a\x16.google.protobuf.Empty(\x01B\bZ\x06proto/"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_goTypes = []any{
	(EventKind)(0),                // 0: api.EventKind
	(EventStatus)(0),              // 1: api.EventStatus
	(*RawEvents)(nil),             // 2: api.RawEvents
	(*RawEvent)(nil),              // 3: api.RawEvent
	(*RawStage)(nil),              // 4: api.RawStage
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_api_proto_depIdxs = []int32{
	3, // 0: api.RawEvents.Events:type_name -> api.RawEvent
	4, // 1: api.RawEvent.Stage:type_name -> api.RawStage
	5, // 2: api.RawEvent.Ts:type_name -> google.protobuf.Timestamp
	0, // 3: api.RawEvent.Kind:type_name -> api.EventKind
	1, // 4: api.RawEvent.Status:type_name -> api.EventStatus
	2, // 5: api.API.SendEvent:input_type -> api.RawEvents
	6, // 6: api.API.SendEvent:output_type -> google.protobuf.Empty
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
